VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/xenial64"
    #config.vm.box="geerlingguy/centos7"
    config.vm.box_check_update = true
    config.vm.define "webserver" do |server|
        server.vm.hostname = "webserver"
        server.vm.box = "ubuntu/xenial64"
        server.vm.provider "virtualbox" do |v|
        server.vm.network "private_network", ip: "192.168.50.30"
        server.vm.network "forwarded_port", guest: 80, host: 8080
        #server.vm.synced_folder ".", "/vagrant"
        #server.vm.synced_folder "/apps/shared", "/shared"
            v.name = "webserver"
            v.memory = 768
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
        server.vm.provision "ansible" do |ansible|
            ansible.playbook = "provisioning/webserver.yml"
        end
    end

    config.vm.define "db1" do |server|
        server.vm.hostname = "db1"
        server.vm.box = "ubuntu/xenial64"
        server.vm.provider "virtualbox" do |v|
        server.vm.network "private_network", ip: "192.168.50.31"
        server.vm.network "forwarded_port", guest: 4000, host: 3306
            v.name = "db1"
            v.memory = 1024
            v.cpus = 1
            v.linked_clone = true
            v.gui = false
        end
        server.vm.provision "ansible" do |ansible|
            ansible.playbook = "provisioning/mysql-server.yml"
        end
    config.vm.synced_folder ".", "/vagrant", owner:"www-data", group:"www-data", mount_options:["dmode=775", "fmode=775"]
    end
end