---
- hosts: all
  sudo: yes
  tasks:
#    - name: update apt cache
#      apt: update_cache=yes
#    - name: install apache
#      apt: name=apache2 update-cache=yes state=latest
#    - name: restart apache
#      service: name=apache2 state=restarted
#    - name: enabled mod_rewrite
#      apache2_module: name=rewrite state=present
#      notify:
#      - restart apache2
#handlers:
#    - name: restart apache2
#      service: name=apache2 state=restarted
#
#    - name: install php
#      apt: name={ {item} } state=present
#      with_items:
#        - php
#        - php-mysql
#        - php-fpm
#        - php-curl
#        - vim
#        - mc

---
- name: Install Apache2 and modules
  apt: name: "{{ item }}"  state: installed
  with_items:
    - python-apt
    - python-pycurl
    -
- name:   Add ondrej repository for later versions of PHP.
  apt_repository: repo='ppa:ondrej/php5' update_cache=yes

- name:    "Install Apache, MySQL, PHP, and other dependencies."
  apt: name={{ item }} state=installed
  with_items:
    - curl
    - apache2
    - php5
    - php5-common
    - php5-mysql
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-dev
    - php5-mcrypt
    - php-apc
    - php-pear

- name: Disable the firewall (since this is for local dev only).
  service: name=ufw state=stopped

- name: "Start Apache, MySQL, and PHP."
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - apache2

- name: Enable Apache rewrite module (required for Joomla).
  apache2_module: name=rewrite state=present
  notify: restart apache

- name: Add Apache virtualhost for Joomla development.
  template:
    src: "templates/drupal.dev.conf.j2"
    dest: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
- name: Symlink Drupal virtualhost to sites-enabled.
  file:
    src: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
    dest: "/etc/apache2/sites-enabled/{{ domain }}.dev.conf"
    state: link
  notify: restart apache
- name: Remove default virtualhost file.
  file:
    path: "/etc/apache2/sites-enabled/000-default"
    state: absent
  notify: restart apache
- name: Create a database for Joomla.
  mysql_db: "db={{ domain }} state=present"